### ISSUE TITLE
edge浏览器中以前使用正常，最新版2.1.6报以下错误：网络错误，请检查网络配置后...

### ISSUE THREAD

**Issue by liuyun198833** [wyndem/ali-video#15]
感谢大佬的插件，在edge浏览器中以前使用正常，最新版2.1.6报以下错误：网络错误，请检查网络配置后...。目前在chrome浏览器上使用正常。不知道如何解决？

**Comment by wyndem** [comment]
感谢你的提问，可以先检查一下本机环境。如果换个浏览器能正常使用说明与脚本没有直接的冲突。
