### ISSUE TITLE
在分享链接页面中选择文件获取链接失败了

### ISSUE THREAD

**Issue by LimitBreaker01** [wyndem/ali-video#19]
<img width="1086" alt="2024-03-06_093409" src="https://github.com/wyndem/ali-video/assets/65392605/b67c3c91-2895-401b-a674-e053d7be3079">
<img width="503" alt="2024-03-05_084104" src="https://github.com/wyndem/ali-video/assets/65392605/00b7f959-3ab5-44c5-9682-9209a829d12b">

昨天就失效了，请修复下，万分感谢。。

**Comment by wyndem** [comment]
官方似乎已经下线了这个接口，目前是不支持了，今天我也会在分享页面中把这个功能暂时关闭掉。等后续如果官方继续上线该接口的时候，我在做调整

**Comment by LimitBreaker01** [comment]
真恶心，以后就得保存随后才能下载。问题是网盘空间有限。

**Comment by ideawhy** [comment]
> 真恶心，以后就得保存随后才能下载。问题是网盘空间有限。

加1，太恶心了
