### ISSUE TITLE
原版双语字幕同时显示，但使用此脚本开启字幕只能显示单语字幕

### ISSUE THREAD

**Issue by zephtung** [wyndem/ali-video#25]
请问有解决方法吗？
![image](https://github.com/wyndem/ali-video/assets/46771585/d1f1e48b-bc65-4ce8-b81a-448d420df872)
![image](https://github.com/wyndem/ali-video/assets/46771585/7a05d821-9eb5-4c0d-b47a-a528f8b73e3b)

**Comment by zephtung** [comment]
应该是原版可以同时显示两行，请问作者可以增加同时显示两行的功能吗？

**Comment by wyndem** [comment]
如果是视频自带的字幕，可以分享给我吗？ 我可以去做适配，如果是外挂字幕的话，那么可以试着切换其他字幕。
![微信截图_20240522214150](https://github.com/wyndem/ali-video/assets/19310581/8cdbefdb-5f3d-4687-b4d4-994343594586)
