### ISSUE TITLE
生产的下载链接不能使用wget下载

### ISSUE THREAD

**Issue by LiMiddleWei** [wyndem/ali-video#3]

**Comment by wyndem** [comment]
会有验证的。直接用Wget可能会有问题





------------------ 原始邮件 ------------------
发件人: LiMiddleWei ***@***.***&gt;
发送时间: 2023年6月28日 19:16
收件人: wyndem/ali-video ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [wyndem/ali-video] 生产的下载链接不能使用wget下载 (Issue #3)
