### ISSUE TITLE
点击链接报错

### ISSUE THREAD

**Issue by jelly8084** [wyndem/ali-video#4]
阿里云盘能显示下载链接 但是点击链接后就显示错误 This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<script id="argent-x-extension" data-extension-id="dlcobpjiigpikoobohmabehhmhfoodbb"/>
<Code>InvalidArgument</Code>
<Message>At least one of AdditionalHeaders is not in request headers.</Message>
<RequestId>64A4C2479EA0073538FAF0C7</RequestId>
<HostId>cn-beijing-data.aliyundrive.net</HostId>
<EC>0002-00000078</EC>
</Error>

**Comment by wyndem** [comment]
如果你复制下载,需要在请求头上加 Referer,值为 https://www.aliyundrive.com/ ，原因是阿里云盘在下载链接上加了验证 。如果是直接点击跳转下载就没有问题。

**Comment by jelly8084** [comment]
我就是直接点击下载的呀 跳转出来就是那个报错页面

**Comment by wyndem** [comment]
已修复，感谢反馈

**Comment by jelly8084** [comment]
已经可以下载了 非常感谢
