### ISSUE TITLE
Aria2 推送失败

### ISSUE THREAD

**Issue by ricl9** [wyndem/ali-video#5]
无法推送到内网aria2下载，一直显示推送失败，只能手动复制链接给aria2

**Comment by wyndem** [comment]
方便提供下当前使用的ara2的版本吗？或者直接发我文件也行

**Comment by wyndem** [comment]
` .\aria2c.exe --enable-rpc --rpc-listen-all   --rpc-secret 123 --rpc-allow-origin-all=true
` 
 可以在Aria2的程序目录下，使用上面命令,RPC密钥为:123。刚刚我用1.36.0的版本测试了下，可以正常推送的

**Comment by flame9468** [comment]
> `.\aria2c.exe --enable-rpc --rpc-listen-all --rpc-secret 123 --rpc-allow-origin-all=true` 可以在Aria2的程序目录下，使用上面命令,RPC密钥为:123。刚刚我用1.36.0的版本测试了下，可以正常推送的

我是docker 版的 1.36.0   p3terx/aria2-pro  也是提示“保存失败,连接不上Aria2配置” RPC密钥是我自定义的

**Comment by wyndem** [comment]
可以检查下推送地址是否能正常连通，在一个在启动时是否加了--rpc-allow-origin-all=true参数。如果都没问题的话，我在根据你的环境进行一个复测，感谢

**Comment by flame9468** [comment]
> 可以检查下推送地址是否能正常连通，在一个在启动时是否加了--rpc-allow-origin-all=true参数。如果都没问题的话，我在根据你的环境进行一个复测，感谢

推送没问题，因为alist推送正常，aria2配置如下
## RPC 设置 ##

# 启用 JSON-RPC/XML-RPC 服务器, 默认:false
enable-rpc=true

# 接受所有远程请求, 默认:false
rpc-allow-origin-all=true

# 允许外部访问, 默认:false
rpc-listen-all=true

# RPC 监听端口, 默认:6800
rpc-listen-port=6800

# RPC 密钥
rpc-secret=我的密钥

# RPC 最大请求大小
rpc-max-request-size=10M

# RPC 服务 SSL/TLS 加密, 默认：false
# 启用加密后必须使用 https 或者 wss 协议连接
# 不推荐开启，建议使用 web server 反向代理，比如 Nginx、Caddy ，灵活性更强。
#rpc-secure=false

# 在 RPC 服务中启用 SSL/TLS 加密时的证书文件(.pem/.crt)
#rpc-certificate=/config/xxx.pem

# 在 RPC 服务中启用 SSL/TLS 加密时的私钥文件(.key)
#rpc-private-key=/config/xxx.key

# 事件轮询方式, 可选：epoll, kqueue, port, poll, select, 不同系统默认值不同
#event-poll=select

**Comment by flame9468** [comment]
问题解决了，供大家参考

解决方法是修改浏览器的安全限制，更改为允许。

Google浏览器也差不多，然后找到不安全的内容，选择允许即可。
![image](https://github.com/wyndem/ali-video/assets/7872399/beb4771b-d1af-4261-828e-efc40f91dfc1)
