### ISSUE TITLE
mac 的motrix 无法下载

### ISSUE THREAD

**Issue by wxmpro** [wyndem/ali-video#8]
mac 和 motrix 都是最新版，没有特别设置，点击推送后，显示是22，跳转到https://github.com/agalwood/Motrix/wiki/Error#22，无法下载。

**Comment by wyndem** [comment]
目前没有对motrix下载器做适配，现在只支持推送到Aria2下载。motrix内部含有Aria2，但不能保证motrix没有对Aria2进行任何处理
